### ISSUE TITLE
ionic 3.19.1 版本config.xml文件中alipay.jar 文件需要调整

### ISSUE THREAD

**Issue by xingducai** [hhjjj1010/cordova-plugin-alipay-v2#12]
`config.xml文件中
     <source-file src="src/android/lib/alipaySdk-20170725.jar" target-dir="libs"/>
修改为
<lib-file src="src/android/lib/alipaySdk-20170725.jar" />`

**Comment by xingducai** [comment]
这个问题是因为cordova 在6.4.0之后调整了android  AndroidManifest.xml文件位置，
导致之前的插件合并AndroidManifest.xml出现bug
调整了ionic cordova platform android@6.4.0解决了

**Comment by rex19001** [comment]
这个config.xml在哪个位置呀？
我在我的config.xnl里并没有看到有source-file这个节点呀

**Comment by xingducai** [comment]
插件的配置文件里面

**Comment by rex19001** [comment]
支付宝又有一个新版本的SDK了 
alipaySdk-20180316 
这个对老的有问题吗？

**Comment by lixiaofeng0831** [comment]
ionic版本默认安装的是android7.0,貌似引用就报错了

**Comment by xingducai** [comment]
降级   ionic  cordoav platform add android@6.4.0
