### ISSUE TITLE
iOS打开支付宝返回App后css动画会加速

### ISSUE THREAD

**Issue by zhyaoang** [hhjjj1010/cordova-plugin-alipay-v2#14]
您好,在使用这个插件时遇到一个问题,页面刷新后仍然存在这种现象,前端使用framework7框架,打开支付宝支付,再返回App目测css动画的速度会增加1/3再打开回来会在已经加速的动画上再加速1/3😊

**Comment by SunXingZ** [comment]
同样遇到这个问题 @hhjjj1010

**Comment by q735423841** [comment]
> 您好,在使用这个插件时遇到一个问题,页面刷新后仍然存在这种现象,前端使用framework7框架,打开支付宝支付,再返回App目测css动画的速度会增加1/3再打开回来会在已经加速的动画上再加速1/3😊

麻烦问下，大大解决了嘛？

**Comment by zhyaoang** [comment]
并没有，考虑考虑其他混合模式框架吧！

**Comment by chavesgu** [comment]
我用的cordova   支付完成后  css也加速了   重复支付几次之后   css变得非常离谱了  @hhjjj1010
