### ISSUE TITLE
调用SDK返回4000

### ISSUE THREAD

**Issue by ouyangrenjian** [hhjjj1010/cordova-plugin-alipay-v2#23]
您好，我是按照上面的步骤安装和使用该插件。但是调用支付宝SDK后返回resultStatus：‘4000’，系统繁忙，请稍后再试。请问是哪里配置错了

**Comment by F88888** [comment]
配置没错，不过是你的手机没安装支付宝APP而已

**Comment by hhjjj1010** [comment]
插件已更新至目前的最新版，如果未安装支付宝APP，应该是要跳转到网页版的支付宝才对
