### ISSUE TITLE
因alipay sdk版本问题导致下架

### ISSUE THREAD

**Issue by k3179** [hhjjj1010/cordova-plugin-alipay-v2#24]
We’ve identified that your app is using the AliPay SDK or library, which facilitates the transmission of phone number information without meeting the prominent disclosure guidelines. Make sure to also post a privacy policy in both the designated field in the Play Developer Console and from within the Play distributed app itself. 

If necessary, you can consult your SDK provider(s) for further information or please upgrade AliPay SDK version to 15.5.5 or higher.

能不能升级sdk版本啊

**Comment by hhjjj1010** [comment]
已更新至15.6.5
