### ISSUE TITLE
安卓支付宝支付流程没走完显示繁忙

### ISSUE THREAD

**Issue by sra31415** [hhjjj1010/cordova-plugin-alipay-v2#29]
我在前端使用
`window.cordova.plugins.alipay.payment(payInfo,(e) => {
          }, (e) => {
            console.log("支付失败" + e.resultStatus);
          });`
然后app点击支付后，跳出支付宝的进度条，但没有显示支付内容，直接显示系统繁忙，请稍后再试，不能完成支付，您知道是怎么回事吗

**Comment by WeihanLi** [comment]
解决了吗？我也遇到了这个问题

**Comment by sra31415** [comment]
> 解决了吗？我也遇到了这个问题

你看看你的参数有没有问题

**Comment by WeihanLi** [comment]
感谢回复，解决了，我是因为生产环境的 APP 打包的时候指定了沙箱环境，去掉使用沙箱环境就可以了
