### ISSUE TITLE
支付成功后无法回调问题

### ISSUE THREAD

**Issue by doudadou** [hhjjj1010/cordova-plugin-alipay-v2#4]
支付宝支付成功后显示空白页，无法回调， 查看Xcode的URL types，已设置过URL Schemes了，但是没回调，请问是哪里的问题呢

**Comment by hhjjj1010** [comment]
AlipaySdk已更新到最新20170725版本。xcode的URL Types上alipay的URL Schemes正确格式应为ali2xxxxxxxxxxxxxxx，2开头的是你的APP_ID。

**Comment by hwlcode** [comment]
xcode的URL Types上alipay的URL Schemes格式正确，依然没有办法回调
